CREATE TABLE ZADVANCEDSETTINGS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZALLONONECHIT INTEGER,
  ZALLOWBARTABSWIPE INTEGER,
  ZALLOWDISCOUNTSONALCOHOL INTEGER,
  ZALLOWEDITINGMODIFIERS INTEGER,
  ZASKFORPARTYNAMEFORPOS INTEGER,
  ZAUTOASSIGNWAITERTOTAKEOUTS INTEGER,
  ZAUTOMATICOUTOFSTOCK INTEGER,
  ZBARTENDERACCESSBARTENDER INTEGER,
  ZBARTENDERCHITS INTEGER,
  ZCHITSORTING INTEGER,
  ZCLOSEMODIFIERSWHENCOMPLETE INTEGER,
  ZCLOSETABLEWHENPAYED INTEGER,
  ZDEFAULTTOSEAT INTEGER,
  ZENABLEAUTOMATICCLOUDBACKUP INTEGER,
  ZENABLEMODIFIERPRICECHANGE INTEGER,
  ZENABLEPARTYCLOUDSYNC INTEGER,
  ZENABLEREPORTCLOUDSYNC INTEGER,
  ZENABLESAFEPRINTING INTEGER,
  ZFASTBARCREDIT INTEGER,
  ZFASTBARDEBIT INTEGER,
  ZIDENTICALCHITSALLPRINTERS INTEGER,
  ZINCLUDECONSOLIDATION INTEGER,
  ZINCLUSIVETAXFORREPORTS INTEGER,
  ZISMAXORDERNUMBERENABLED INTEGER,
  ZLANDSCAPEBUTTONCASH INTEGER,
  ZLANDSCAPEBUTTONCREDIT INTEGER,
  ZLANDSCAPEBUTTONDEBIT INTEGER,
  ZLANDSCAPEBUTTONEXACT INTEGER,
  ZLANDSCAPEBUTTONNOSALE INTEGER,
  ZLANDSCAPEBUTTONPAYPAL INTEGER,
  ZLANDSCAPEBUTTONPRINT INTEGER,
  ZLANDSCAPEBUTTONSENDALL INTEGER,
  ZLANDSCAPEBUTTONSMART1 INTEGER,
  ZLANDSCAPEBUTTONSMART2 INTEGER,
  ZLANDSCAPEBUTTONSMART3 INTEGER,
  ZLANDSCAPEBUTTONTRANSFER INTEGER,
  ZLOADPREVIOUSRESTAURANTONLOAD INTEGER,
  ZLOCKMENUTOGGLE INTEGER,
  ZLOCKSTAFFTOASSIGNEDTABLES INTEGER,
  ZLOCKSTAFFTOASSIGNEDTAKEOUTS INTEGER,
  ZMAXORDERNUMBER INTEGER,
  ZMENUITEMICONMODE INTEGER,
  ZONLINEORDERINGRECEIPTPRINTINGENABLED INTEGER,
  ZOPENDRAWERFORCASH INTEGER,
  ZOPENDRAWERFORCREDIT INTEGER,
  ZPASSWORDFORCASHDRAWER INTEGER,
  ZPRINTALLONORDERINPUT INTEGER,
  ZPRINTCLOCKINOUTCHIT INTEGER,
  ZPRINTDISCOUNTEDITEMS INTEGER,
  ZPRINTMODIFIERSRED INTEGER,
  ZPRINTSALESCATEGORIES INTEGER,
  ZPRINTSHORTNAME INTEGER,
  ZPRINTSMALLCHITS INTEGER,
  ZPRINTTABLEINFORED INTEGER,
  ZPRINTVOIDCHITS INTEGER,
  ZPRINTWAITERCREDITREPORT INTEGER,
  ZPRINTZEROPRICEDMENUITEMS INTEGER,
  ZPRINTZEROPRICEDMODIFIERS INTEGER,
  ZPROCEEDTOORDERINPUT INTEGER,
  ZPROMPTFORADMINPASSWORDONLOAD INTEGER,
  ZREQUIREAUTH INTEGER,
  ZREQUIREMANAGERFORGRATUITY INTEGER,
  ZREQUIREMANAGERFORMOVEPARTY INTEGER,
  ZREQUIREMANAGERTODELETEITEM INTEGER,
  ZREQUIREMANAGERTODISCOUNT INTEGER,
  ZREQUIREMANAGERTOVOID INTEGER,
  ZREQUIREPASSCODETOTRANSFERTABLES INTEGER,
  ZREQUIREPASSCODETOTRANSFERTAKEOUTS INTEGER,
  ZRETURNAFTERSENDING INTEGER,
  ZRETURNFROMBILLPAYMENT INTEGER,
  ZSHOWCONTACTS INTEGER,
  ZSHOWDISCOUNTSONBILL INTEGER,
  ZSHOWEMAILRECEIPTWHENCLOSING INTEGER,
  ZSHOWGATEWAYTIPLINE INTEGER,
  ZSHOWMENUITEMMODIFIER INTEGER,
  ZSHOWNAMEONBARSTOOL INTEGER,
  ZSHOWNONINTEGRATEDPAYMENTS INTEGER,
  ZSHOWPRINTANDCLOSE INTEGER,
  ZSHOWPRINTSUCCESSPOPUP INTEGER,
  ZSHOWTOUCHBISTROONRECEIPT INTEGER,
  ZSHOWVOIDEDITEMSONBILL INTEGER,
  ZTIMEOUTINTERVAL INTEGER,
  ZTRACKDELETEDITEMS INTEGER,
  ZUNSELECTEDMODIFIERSWARNING INTEGER,
  ZUNSENTITEMSWARNING INTEGER,
  ZMODIFIERSUFFIX VARCHAR,
  ZUUID VARCHAR,
  ZDATA BLOB,
  ZSENDITEMSONCHECKOUT INTEGER
);
CREATE TABLE ZALLERGEN (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZTYPE INTEGER,
  ZRESTAURANT INTEGER,
  ZUUID VARCHAR
);
CREATE TABLE ZBILLCHANGELOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZTIMESTAMP TIMESTAMP,
  ZUPLOADTIME TIMESTAMP,
  ZBILLNUMBER VARCHAR,
  ZCLOSEDDATAUPLOADPAYLOAD VARCHAR,
  ZCLOSEDDATAUPLOADRESPONSE VARCHAR,
  ZCLOUDSYNCREASON VARCHAR,
  ZPAIDORDERUUID VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZBILLHEADERSETTINGS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZINCLUDEBILLNUMBER INTEGER,
  ZINCLUDEDAILYORDER INTEGER,
  ZINCLUDEDISCOUNTTOTAL INTEGER,
  ZINCLUDEORDERNUMBER INTEGER,
  ZINCLUDESENDTIME INTEGER,
  ZINCLUDETABLENAME INTEGER,
  ZINCLUDETAX1NUMBER INTEGER,
  ZINCLUDETAX2NUMBER INTEGER,
  ZINCLUDETAX3NUMBER INTEGER,
  ZINCLUDEWAITERNAME INTEGER,
  ZTIPGUIDESTATUS INTEGER,
  ZTIPGUIDEONE FLOAT,
  ZTIPGUIDETHREE FLOAT,
  ZTIPGUIDETWO FLOAT,
  ZLOGOPATH VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZBREAKTYPE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZDURATIONINMINUTES INTEGER,
  ZISPAID INTEGER,
  ZCREATEDAT TIMESTAMP,
  ZUPDATEDAT TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZCARDTYPE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZANALYTICSCARDTYPE INTEGER,
  ZRESTAURANTINFO INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZCHANGELOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZTIMESTAMP TIMESTAMP,
  ZCHANGETYPE VARCHAR,
  ZCHANGETYPEDETAILS VARCHAR,
  ZOBJECTREFERENCE VARCHAR,
  ZOBJECTREFERENCETYPE VARCHAR,
  ZUSER VARCHAR,
  ZUUID VARCHAR,
  ZVALUECHANGEDFROM VARCHAR,
  ZVALUECHANGEDTO VARCHAR
);
CREATE TABLE ZCHITHEADERSETTINGS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBOTTOMSPACE INTEGER,
  ZCONSOLIDATEBYCOURSE INTEGER,
  ZFOOTERINCLUDECONSOLIDATION INTEGER,
  ZFOOTERINCLUDEORDERNUMBER INTEGER,
  ZFOOTERINCLUDEPARTYNAME INTEGER,
  ZFOOTERINCLUDESENDTIME INTEGER,
  ZFOOTERINCLUDETABLENAME INTEGER,
  ZFOOTERINCLUDETABLESIZE INTEGER,
  ZFOOTERINCLUDEWAITERNAME INTEGER,
  ZHEADERINCLUDECONSOLIDATION INTEGER,
  ZHEADERINCLUDELARGEPARTYNAME INTEGER,
  ZHEADERINCLUDELARGETABLENAME INTEGER,
  ZHEADERINCLUDEORDERNUMBER INTEGER,
  ZHEADERINCLUDEPARTYNAME INTEGER,
  ZHEADERINCLUDESENDTIME INTEGER,
  ZHEADERINCLUDETABLENAME INTEGER,
  ZHEADERINCLUDETABLESIZE INTEGER,
  ZHEADERINCLUDETAKEOUTHEADER INTEGER,
  ZHEADERINCLUDEWAITERNAME INTEGER,
  ZTOPSPACE INTEGER,
  ZUUID VARCHAR
);
CREATE TABLE ZCLOUDSYNCLOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZACTIONTYPE INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZTIMESTAMP TIMESTAMP,
  ZNEXTVALUE VARCHAR,
  ZOBJECTPROPERTY VARCHAR,
  ZOBJECTTYPE VARCHAR,
  ZOBJECTUUID VARCHAR,
  ZOLDVALUE VARCHAR
);
CREATE TABLE ZCONNECTEDIPADS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZLASTCONNECTEDTIME TIMESTAMP,
  ZAPPLICATIONTYPE VARCHAR,
  ZDEVICENAME VARCHAR,
  ZDEVICETYPE VARCHAR,
  ZIOSVERSION VARCHAR,
  ZUNIQUEIDENTIFIER VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZCUSTOMERINFO (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZCUSTOMER INTEGER,
  ZADDRESS VARCHAR,
  ZCITY VARCHAR,
  ZCOUNTRY VARCHAR,
  ZEMAIL VARCHAR,
  ZNOTES VARCHAR,
  ZPHONE VARCHAR,
  ZPROVINCE VARCHAR,
  ZURL VARCHAR,
  ZUUID VARCHAR,
  ZZIP VARCHAR
);
CREATE TABLE ZCUSTOMTAKEOUTTYPE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRESTAURANT INTEGER,
  ZDELETEDAT TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZDAILYMODIFICATIONLOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZSYNCSTATUS INTEGER,
  ZCALENDARDAY TIMESTAMP,
  ZLASTMODIFIED TIMESTAMP,
  ZUUID VARCHAR
);
CREATE TABLE ZDEPOSIT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRESERVATION INTEGER,
  ZAMOUNT FLOAT
);
CREATE TABLE ZDISCOUNT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_INDEX INTEGER,
  ZI_TYPE INTEGER,
  ZRETURNSINVENTORY INTEGER,
  ZTAXABLE INTEGER,
  /* not used */
  ZORDERITEM INTEGER,
  ZI_AMOUNT FLOAT,
  ZVOIDDATE TIMESTAMP,
  ZDISCOUNTDESCRIPTION VARCHAR,
  ZMANAGERUUID VARCHAR,
  ZUUID VARCHAR,
  ZWAITERUUID VARCHAR
);
CREATE TABLE ZGIFTCARDTRANSACTIONLOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZSTATUS INTEGER,
  ZTYPE INTEGER,
  ZWAITER INTEGER,
  ZBALANCEAFTER FLOAT,
  ZBALANCEBEFORE FLOAT,
  ZCHANGEINVALUE FLOAT,
  ZDATE TIMESTAMP,
  ZGIFTCARDID VARCHAR,
  ZSTATUSMESSAGE VARCHAR,
  ZUUID VARCHAR,
  ZWAITERUUID VARCHAR
);
CREATE TABLE ZINGREDIENT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZPURCHASEMEASURE INTEGER,
  ZRECIPEMEASURE INTEGER,
  ZSYNCSTATUS INTEGER,
  ZCOUNT FLOAT,
  ZCREATEDATE TIMESTAMP,
  ZDELETEDAT TIMESTAMP,
  ZLASTUPDATED TIMESTAMP,
  ZLOWSTOCKTHRESHOLD FLOAT,
  ZPURCHASECOST FLOAT,
  ZRECIPECOST FLOAT,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZINGREDIENTFORMENUITEM (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZINGREDIENT INTEGER,
  ZMENUITEM INTEGER,
  ZRECIPEMEASURE INTEGER,
  ZQUANTITY FLOAT,
  ZUUID VARCHAR
);
CREATE TABLE ZINGREDIENTLOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZSYNCSTATUS INTEGER,
  ZTYPE INTEGER,
  ZINGREDIENT INTEGER,
  ZWAITER INTEGER,
  ZAMOUNT FLOAT,
  ZDATEADDED TIMESTAMP,
  ZNEXTAMOUNT FLOAT,
  ZPREVIOUSAMOUNT FLOAT,
  ZINGREDIENTUUID VARCHAR,
  ZUUID VARCHAR,
  ZWAITERUUID VARCHAR
);
CREATE TABLE ZINGREDIENTSUMMARYLOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZINGREDIENT INTEGER,
  ZADJUSTMENTCOUNT FLOAT,
  ZDATE TIMESTAMP,
  ZENDCOUNT FLOAT,
  ZINGREDIENTCOST FLOAT,
  ZPURCHASECOUNT FLOAT,
  ZSALESCOUNT FLOAT,
  ZSTARTCOUNT FLOAT,
  ZINGREDIENTUUID VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZINTEGRATION (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZISACTIVE INTEGER,
  ZRESTAURANT INTEGER,
  ZNAME VARCHAR,
  ZPASSWORD VARCHAR,
  ZSETTINGS VARCHAR,
  ZUSERNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZKITCHENSTATIONCHIT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZINDEX INTEGER,
  ZISCLOSED INTEGER,
  ZORDER INTEGER,
  ZSTATION INTEGER,
  ZVERSION FLOAT,
  ZUUID VARCHAR
);
CREATE TABLE ZKITCHENSTATIONMODIFIER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZPARENTMODIFIER INTEGER,
  ZPARENTORDERITEM INTEGER,
  ZVERSION FLOAT,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZKITCHENSTATIONORDER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZISVIP INTEGER,
  ZISVOID INTEGER,
  ZSTATUS INTEGER,
  ZAPPROXFINISHTIME TIMESTAMP,
  ZFINISHTIME TIMESTAMP,
  ZSENTTIME TIMESTAMP,
  ZSTARTTIME TIMESTAMP,
  ZVERSION FLOAT,
  ZORDERNUMBER VARCHAR,
  ZTABLENAME VARCHAR,
  ZTABLESIZE VARCHAR,
  ZTAKEOUTSTATUS VARCHAR,
  ZUUID VARCHAR,
  ZWAITERID VARCHAR,
  ZWAITERNAME VARCHAR
);
CREATE TABLE ZKITCHENSTATIONORDERITEM (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZAPPROXCOOKINGTIME INTEGER,
  ZCOURSE INTEGER,
  ZINDEX INTEGER,
  ZISVOID INTEGER,
  ZSEATINDEX INTEGER,
  ZSTATUS INTEGER,
  ZORDER INTEGER,
  ZAPPROXFINISHTIME TIMESTAMP,
  ZFINISHTIME TIMESTAMP,
  ZQUANTITY FLOAT,
  ZSTARTTIME TIMESTAMP,
  ZVERSION FLOAT,
  ZNAME VARCHAR,
  ZPARENTMENUITEMID VARCHAR,
  ZSEATNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZLOYALTYACTIVITYLOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZACTIVITYTYPE INTEGER,
  ZLOYALTYTYPE INTEGER,
  ZWAITER INTEGER,
  ZAMOUNT FLOAT,
  ZCREATEDAT TIMESTAMP,
  ZREVERSEDAT TIMESTAMP,
  ZPENDINGTRANSACTIONDATA VARCHAR,
  ZREVERSEDBY VARCHAR,
  ZTRANSACTIONID VARCHAR,
  ZUSERID VARCHAR,
  ZUSERNAME VARCHAR,
  ZUUID VARCHAR,
  ZWAITERUUID VARCHAR
);
CREATE TABLE ZMENUBOARDSETTINGS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRESTAURANTTITLESCREENIMAGEEXISTS INTEGER,
  ZTHEMEMODE INTEGER,
  ZUUID VARCHAR
);
CREATE TABLE ZMENUCATEGORYINFOFORMENUPAGE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZPOSITION INTEGER,
  ZMENUCATEGORY INTEGER,
  ZMENUPAGE INTEGER,
  ZUUID VARCHAR
);
CREATE TABLE ZMENUPAGE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZENABLED INTEGER,
  ZRANK INTEGER,
  ZUSEFORMENUBOARD INTEGER,
  ZUSEFORONLINEORDERING INTEGER,
  ZRESTAURANTINFO INTEGER,
  ZTBMENULOCK INTEGER,
  ZDELETEDAT TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZMESSAGE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZISREAD INTEGER,
  ZTYPE INTEGER,
  ZSENTTIME TIMESTAMP,
  ZMESSAGE VARCHAR,
  ZPAIDORDERID VARCHAR,
  ZRECIPIENT VARCHAR,
  ZSENDER VARCHAR,
  ZSENDERIMAGEURL VARCHAR,
  ZSUBJECT VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZMODIFIER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_INDEX INTEGER,
  ZREQUIREDMODIFIER INTEGER,
  ZCONTAINERORDERITEM INTEGER,
  ZMENUITEM INTEGER,
  ZMODIFIERGROUP INTEGER,
  ZMODIFIERGROUPFORMENUITEM INTEGER,
  ZORDERITEM INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZI_PRICE FLOAT,
  ZI_NAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZMODIFIERGROUPFORMENUITEM (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_INDEX INTEGER,
  ZI_REQUIREDSELECTIONS INTEGER,
  ZMENUITEM INTEGER,
  ZMODIFIERGROUP INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZUUID VARCHAR
);
CREATE TABLE ZONLINEORDER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBILLPRINTFAILED INTEGER,
  ZCANCELLATIONCODEOLD INTEGER,
  ZFULFILLMENTTYPE INTEGER,
  ZISPREACCEPTED INTEGER,
  ZISVENUECANCELLABLE INTEGER,
  ZNEEDSACKNOWLEDGMENT INTEGER,
  ZORDERITEMCOUNT INTEGER,
  ZSENDFAILED INTEGER,
  ZSTATEOLD INTEGER,
  ZSYNCSTATUS INTEGER,
  ZCLOSEDTAKEOUT INTEGER,
  ZTAKEOUT INTEGER,
  ZACCEPTEDAT TIMESTAMP,
  ZCANCELLEDAT TIMESTAMP,
  ZCOMMISSIONTOTAL FLOAT,
  ZCOMPLETEDAT TIMESTAMP,
  ZCREATEDAT TIMESTAMP,
  ZDECLINEDAT TIMESTAMP,
  ZORDERTOTAL FLOAT,
  ZREMITTABLETAXTOTAL FLOAT,
  ZUPDATEDAT TIMESTAMP,
  ZVENUETIPTOTAL FLOAT,
  ZCANCELLATIONCODENEW VARCHAR,
  ZCANCELLATIONDETAILS VARCHAR,
  ZGATEWAYID VARCHAR,
  ZGATEWAYORDERREFERENCEID VARCHAR,
  ZNOTE VARCHAR,
  ZORDERJSON VARCHAR,
  ZORDERREQUESTID VARCHAR,
  ZPROVIDERIDSTRING VARCHAR,
  ZPROVIDERNAME VARCHAR,
  ZPROVIDERORDERREFERENCEID VARCHAR,
  ZRECIPIENTADDRESS VARCHAR,
  ZRECIPIENTNAME VARCHAR,
  ZRECIPIENTPHONE VARCHAR,
  ZSTATENEW VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZORDERITEM (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_COURSE INTEGER,
  ZI_INDEX INTEGER,
  ZI_SEND INTEGER,
  ZI_SENT INTEGER,
  ZISRETURN INTEGER,
  ZMENUITEM INTEGER,
  ZMENUPAGE INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZI_OPENPRICE FLOAT,
  ZI_QUANTITY FLOAT,
  ZMENUITEMCOST FLOAT,
  ZONLINEORDERPRICE FLOAT,
  ZRECIPECOST FLOAT,
  ZSENTTIME TIMESTAMP,
  ZMENUITEMUUID VARCHAR,
  ZUUID VARCHAR,
  ZWAITERID VARCHAR
);
CREATE TABLE ZORDERITEMLOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZMENUITEMVERSION TIMESTAMP,
  ZORDERITEMCREATEDATE TIMESTAMP,
  ZQUANTITY FLOAT,
  ZTOTALPRICEWITHMODIFIERS FLOAT,
  ZMANAGER VARCHAR,
  ZMENUITEM VARCHAR,
  ZORDERNUMBER VARCHAR,
  ZUUID VARCHAR,
  ZWAITER VARCHAR
);
CREATE TABLE ZPARTY (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_HASSENTITEMS INTEGER,
  ZI_ONCOURSE INTEGER,
  ZI_SPLIT INTEGER,
  ZI_STARTEDPAYING INTEGER,
  ZISAUTOGRATUITYAPPLIED INTEGER,
  ZMAXSEATCOUNT INTEGER,
  ZOTPAYMENTSTATUS INTEGER,
  ZSYNCSTATUS INTEGER,
  ZDEPOSIT INTEGER,
  ZORDER INTEGER,
  ZTABLE INTEGER,
  ZTABLEORDER INTEGER,
  ZTAKEOUT INTEGER,
  ZI_GRATUITY FLOAT,
  ZLASTMODIFIED TIMESTAMP,
  ZSEATED TIMESTAMP,
  ZNAME VARCHAR,
  ZREUPDATA VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPAYMENT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_INDEX INTEGER,
  ZI_TYPE INTEGER,
  ZACCOUNT INTEGER,
  ZCUSTOMER INTEGER,
  ZPAYMENTGATEWAYTRANSACTIONINFO INTEGER,
  ZPAYMENTGROUP INTEGER,
  ZBALANCE FLOAT,
  ZCREATEDATE TIMESTAMP,
  ZI_AMOUNT FLOAT,
  ZI_CHANGE FLOAT,
  ZTIP FLOAT,
  ZAUTH VARCHAR,
  ZCARDEXPIRY VARCHAR,
  ZCARDHOLDER VARCHAR,
  ZCARDNUMBER VARCHAR,
  ZCARDTYPE VARCHAR,
  ZMERCURYRESPONSEBASE64 VARCHAR,
  ZUUID VARCHAR,
  ZI_REFUNDABLEAMOUNT FLOAT,
  ZORIGINALPAYMENTUUID VARCHAR
);
CREATE TABLE ZPAYMENTLOG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZISAPPLIED INTEGER,
  ZPAYMENTGATEWAYTRANSACTIONTYPE INTEGER,
  ZPAYMENTGATEWAYTYPE INTEGER,
  ZPAYMENTTYPE INTEGER,
  ZTRANSACTIONTYPE INTEGER,
  ZACCOUNT INTEGER,
  ZAMOUNT FLOAT,
  ZDATE TIMESTAMP,
  ZTIP FLOAT,
  ZAPPLICATIONTYPE VARCHAR,
  ZAPPLICATIONTYPEDETAILS VARCHAR,
  ZAUTHCODE VARCHAR,
  ZCARDDESCRIPTION VARCHAR,
  ZCARDHOLDER VARCHAR,
  ZCARDNUMBER VARCHAR,
  ZPAYMENTGATEWAYREFERENCECODE VARCHAR,
  ZPAYMENTUUID VARCHAR,
  ZPAYPALCUSTOMERID VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPAYMENTS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_INDEX INTEGER,
  ZPAIDORDER INTEGER,
  ZPARTY INTEGER,
  ZUUID VARCHAR
);
CREATE TABLE ZPAYOUT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZTYPE INTEGER,
  ZREASON INTEGER,
  ZTABLE INTEGER,
  ZWAITER INTEGER,
  ZAMOUNT FLOAT,
  ZTIME TIMESTAMP,
  ZCOMMENT VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPAYOUTREASON (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDAT TIMESTAMP,
  ZDELETEDAT TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPERIPHERAL (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZISDEFAULT INTEGER,
  ZTYPE INTEGER,
  ZRESTAURANT INTEGER,
  ZIPADDRESS VARCHAR,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPREAUTH (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZPAYMENTSOBJECT INTEGER,
  ZAUTHORIZE FLOAT,
  ZGRATUITY FLOAT,
  ZPURCHASE FLOAT,
  ZACQREFDATA VARCHAR,
  ZAUTHCODE VARCHAR,
  ZCARDNUMBER VARCHAR,
  ZCARDTYPE VARCHAR,
  ZMERCURYRESPONSEBASE64 VARCHAR,
  ZRECORDNO VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPRINTREFERENCE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZDATE TIMESTAMP,
  ZSUBTOTAL FLOAT,
  ZDOCUMENTSHA1 VARCHAR,
  ZTRANSACTIONNUMBER VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZRECIPEMEASURE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZMEASURE INTEGER,
  ZINGREDIENT INTEGER,
  ZCONVERSIONRATIO FLOAT,
  ZCREATEDAT TIMESTAMP,
  ZDELETEDAT TIMESTAMP,
  ZUUID VARCHAR
);
CREATE TABLE ZREGISTERBUTTON (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZROW INTEGER,
  ZSECTION INTEGER,
  ZSTYLE INTEGER,
  ZRESTAURANT INTEGER,
  ZKEY VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZREGISTEREDDEVICES (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZDEVICETYPE INTEGER,
  ZDELETEDAT TIMESTAMP,
  ZLASTCONNECTEDDATE TIMESTAMP,
  ZREGISTEREDAT TIMESTAMP,
  ZDEVICENAME VARCHAR,
  ZDEVICEVENDORID VARCHAR,
  ZHARDWAREDETAILS VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZREPORTDEFAULTS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZDEFAULTSORT INTEGER,
  ZREPORTIDENTIFIER VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZREPORTIDENTIFIER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_INDEX INTEGER,
  ZTEMPLATE INTEGER,
  ZREPORTIDENTIFIER VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZRESTAURANTPAYMENTGATEWAY (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZAUTOMATICALLYCLOSETABLE INTEGER,
  ZCOUNTRYTYPE INTEGER,
  ZDISABLETERMINALPRINTING INTEGER,
  ZENABLEKEYEDENTRY INTEGER,
  ZENABLETIPS INTEGER,
  ZENABLETIPSPERCENTAGE INTEGER,
  ZISDEFAULT INTEGER,
  ZISZEROAUTHENABLED INTEGER,
  ZMERCHANTTYPE INTEGER,
  ZSHOWADDRESSFIELDSFORHOSTEDCHECKOUT INTEGER,
  ZTERMINALDISPLAYMODE INTEGER,
  ZRESTAURANT INTEGER,
  ZREQUIRESIGNATUREABOVEAMOUNT FLOAT,
  ZAUTHORIZEDTERMINALS VARCHAR,
  ZCONTEXT VARCHAR,
  ZECRNUMBER VARCHAR,
  ZHOSTEDID VARCHAR,
  ZHOSTEDPASSWORD VARCHAR,
  ZMERCHANTCOUNTRYCODE VARCHAR,
  ZMERCHANTCURRENCYCODE VARCHAR,
  ZMERCHANTID VARCHAR,
  ZMERCHANTKEY VARCHAR,
  ZMERCHANTNAME VARCHAR,
  ZMERCHANTPASSWORD VARCHAR,
  ZMERCHANTSITEID VARCHAR,
  ZNAME VARCHAR,
  ZSETTINGS VARCHAR,
  ZSTOREID VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZSTOREDPAYMENTMETHOD (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZPARTY INTEGER,
  ZDATE TIMESTAMP,
  ZNAME VARCHAR,
  ZTOKEN VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZTABLE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_SEATS INTEGER,
  ZI_SIZE INTEGER,
  ZI_TYPE INTEGER,
  ZBOTTOMCHILD INTEGER,
  ZFLOORPLAN INTEGER,
  ZLEFTCHILD INTEGER,
  ZPARENT INTEGER,
  ZPARTY INTEGER,
  ZRIGHTCHILD INTEGER,
  ZSECTION INTEGER,
  ZTOPCHILD INTEGER,
  ZWAITER INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZI_OLDBOUNDS VARCHAR,
  ZI_POSITION VARCHAR,
  ZI_POSITION2 VARCHAR,
  ZNAME VARCHAR,
  ZTABLECODE VARCHAR,
  ZUUID VARCHAR,
  ZWAITERUUID VARCHAR
);
CREATE TABLE ZTBMENUSETTING (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZALWAYSSHOWMODIFIERS INTEGER,
  ZDISMISSMODIFIERS INTEGER,
  ZISENABLED INTEGER,
  ZISLOCKENABLED INTEGER,
  ZISNAMEREQUIREDONORDER INTEGER,
  ZISORDERINGENABLED INTEGER,
  ZLAYOUTTYPE INTEGER,
  ZLOCKEDMENUMODE INTEGER,
  ZLOCKEDVIEW INTEGER,
  ZPAYMENTMETHOD INTEGER,
  ZRESTAURANTTITLESCREENIMAGEEXISTS INTEGER,
  ZSHOWALLERGENS INTEGER,
  ZSHOWINGREDIENTS INTEGER,
  ZSHOWPRICES INTEGER,
  ZSMARTORDERINGMODE INTEGER,
  ZSMARTORDERINGTHRESHOLD INTEGER,
  ZLOCKEDMENU INTEGER,
  ZBACKGROUNDIMAGE VARCHAR,
  ZCASHINSTRUCTIONSTRING VARCHAR,
  ZCREDITDEBITINSTRUCTIONSTRING VARCHAR,
  ZORDERCONFIRMATIONSTRING VARCHAR,
  ZORDERNAMEINSTRUCTIONSTRING VARCHAR,
  ZORDERNAMETEXTFIELDPLACEHOLDER VARCHAR,
  ZUUID VARCHAR,
  ZVALIDATIONREQUIREDINSTRUCTIONSTRING VARCHAR
);
CREATE TABLE ZTBSCHEDULE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZISFRIDAY INTEGER,
  ZISMONDAY INTEGER,
  ZISSATURDAY INTEGER,
  ZISSUNDAY INTEGER,
  ZISTHURSDAY INTEGER,
  ZISTUESDAY INTEGER,
  ZISWEDNESDAY INTEGER,
  ZMENU INTEGER,
  ZMENUCATEGORY INTEGER,
  ZMENUPAGE INTEGER,
  ZMENUPROMOTION INTEGER,
  ZENDTIME TIMESTAMP,
  ZSTARTTIME TIMESTAMP,
  ZUUID VARCHAR
);
CREATE TABLE ZTOUCHBISTROACCOUNTSETTINGS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_ONLINEORDERSENABLED INTEGER,
  ZI_SHOULDPOLL INTEGER,
  ZACCOUNTNAME VARCHAR,
  ZRESTAURANTNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZTOUCHBISTROANALYTICS (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBILLSPAID INTEGER,
  ZCASHCOUNT INTEGER,
  ZCREDITCOUNT INTEGER,
  ZOTHERCOUNT INTEGER,
  ZPAYPALCOUNT INTEGER,
  ZCASHAMOUNT FLOAT,
  ZCREDITAMOUNT FLOAT,
  ZOTHERAMOUNT FLOAT,
  ZPAYPALAMOUNT FLOAT,
  ZCARDTYPESTRING VARCHAR,
  ZDEVICETYPELIST VARCHAR,
  ZPAYMENTTYPELIST VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZWAITERROLE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZROLE INTEGER,
  ZWAITER INTEGER,
  ZRATEOFPAY FLOAT,
  ZUUID VARCHAR
);
CREATE TABLE ZWALL (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_COLOR INTEGER,
  ZI_SIZE INTEGER,
  ZFLOORPLAN INTEGER,
  ZI_CORNER1POSITION VARCHAR,
  ZI_CORNER2POSITION VARCHAR,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE Z_METADATA (
  Z_VERSION INTEGER PRIMARY KEY,
  Z_UUID VARCHAR(255),
  Z_PLIST BLOB
);
CREATE TABLE Z_MODELCACHE (Z_CONTENT BLOB);
CREATE TABLE ZMENUITEM (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBACKGROUNDCOLOR INTEGER,
  ZI_COURSE INTEGER,
  ZI_EXCLUDETAX1 INTEGER,
  ZI_EXCLUDETAX2 INTEGER,
  ZI_EXCLUDETAX3 INTEGER,
  ZI_HIDDEN INTEGER,
  ZI_INDEX INTEGER,
  ZI_WINEID INTEGER,
  ZINSTOCK INTEGER,
  ZISARCHIVED INTEGER,
  ZISRETURNABLE INTEGER,
  ZPRINTSEPERATECHIT INTEGER,
  ZREQUIREMANAGER INTEGER,
  ZSHOWINPUBLICMENU INTEGER,
  ZTYPE INTEGER,
  ZUSERECIPECOST INTEGER,
  ZUSEDFORGIFTCARDS INTEGER,
  ZCATEGORY INTEGER,
  ZREQUIRESVALIDATIONONKIOSK INTEGER,
  ZRESTAURANT INTEGER,
  ZACTUALCOST FLOAT,
  ZAPPROXCOOKINGTIME FLOAT,
  ZCREATEDATE TIMESTAMP,
  ZI_COUNT FLOAT,
  ZI_PRICE FLOAT,
  ZI_WARNCOUNT FLOAT,
  ZVERSION TIMESTAMP,
  ZCATEGORYNAME VARCHAR,
  ZCATEGORYUUID VARCHAR,
  ZI_FULLIMAGE VARCHAR,
  ZI_PARENTUUID VARCHAR,
  ZI_THUMBIMAGE VARCHAR,
  ZITEMDESCRIPTION VARCHAR,
  ZNAME VARCHAR,
  ZPUBLICMENUCLOUDIMAGEFULLURL VARCHAR,
  ZPUBLICMENUCLOUDIMAGETHUMBNAILURL VARCHAR,
  ZRECIPE VARCHAR,
  ZSHORTNAME VARCHAR,
  ZUPC VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZAPPLIEDBREAK (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBREAKTYPEDURATIONINMINUTES INTEGER,
  ZBREAKTYPEISPAID INTEGER,
  ZSYNCSTATUS INTEGER,
  ZSHIFT INTEGER,
  ZCREATEDAT TIMESTAMP,
  ZENDTIME TIMESTAMP,
  ZSTARTTIME TIMESTAMP,
  ZUPDATEDAT TIMESTAMP,
  ZBREAKTYPENAME VARCHAR,
  ZENDEDBYWAITERUUID VARCHAR,
  ZSHIFTUUID VARCHAR,
  ZSTARTEDBYWAITERUUID VARCHAR,
  ZUPDATEDBYWAITERUUID VARCHAR,
  ZUUID VARCHAR,
  ZWAITERUUID VARCHAR
);
CREATE TABLE ZSHIFT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZSYNCSTATUS INTEGER,
  ZSTAFFROLE INTEGER,
  ZWAITER INTEGER,
  ZCLOCKIN TIMESTAMP,
  ZCLOCKOUT TIMESTAMP,
  ZCREATEDATE TIMESTAMP,
  ZDELETEDAT TIMESTAMP,
  ZLASTMODIFIED TIMESTAMP,
  ZRATEOFPAY FLOAT,
  ZTIP FLOAT,
  ZLASTMODIFIEDBY VARCHAR,
  ZSTAFFROLEUUID VARCHAR,
  ZUUID VARCHAR,
  ZWAITERUUID VARCHAR
);
CREATE TABLE ZDATAMIGRATION (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZENDEDAT TIMESTAMP,
  ZSTARTEDAT TIMESTAMP,
  ZAPPLIEDINAPPVERSION VARCHAR,
  ZRAWMIGRATIONACTION VARCHAR,
  ZRAWSTATUS VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZORDER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBILLNUMBER INTEGER,
  ZI_EXCLUDETAX1 INTEGER,
  ZI_EXCLUDETAX2 INTEGER,
  ZI_EXCLUDETAX3 INTEGER,
  ZI_INDEX INTEGER,
  ZPAIDORDER INTEGER,
  ZPARTY INTEGER,
  ZPARTYASSPLITORDER INTEGER,
  ZTEMPPARTY INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZI_SPLITBY FLOAT,
  ZGROUPCOLORHEXSTRING VARCHAR,
  ZNOTE VARCHAR,
  ZORDERNUMBER VARCHAR,
  ZUUID VARCHAR,
  ZLOYALTYTRANSACTIONXREFID VARCHAR
);
CREATE TABLE ZMENUCATEGORY (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBACKGROUNDCOLOR INTEGER,
  ZI_COURSE INTEGER,
  ZI_CUSTOM INTEGER,
  ZI_INDEX INTEGER,
  ZI_SORTING INTEGER,
  ZI_TAX1 INTEGER,
  ZI_TAX2 INTEGER,
  ZI_TAX3 INTEGER,
  ZISHIDDEN INTEGER,
  ZSHOWINPUBLICMENU INTEGER,
  ZTYPE INTEGER,
  ZHIDDENSCHEDULE INTEGER,
  ZKITCHENDISPLAY INTEGER,
  ZPRINTER INTEGER,
  ZRESTAURANTINFOASUNUSED INTEGER,
  ZRESTAURANTINFOASUSED INTEGER,
  ZSTATION INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZI_IMAGE VARCHAR,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE IF NOT EXISTS "Z_40MENUITEMS" (
  Z_40MENU INTEGER,
  Z_44MENUITEMS3 INTEGER,
  PRIMARY KEY (Z_40MENU, Z_44MENUITEMS3)
);
CREATE TABLE ZRESTAURANTINFO (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZCOLOMBIATAXTYPE INTEGER,
  ZCUSTOMERFACINGDISPLAYCOUNT INTEGER,
  ZGRATUITYSUBTOTALCALCULATIONMODE INTEGER,
  ZI_AIRPRINTMODE INTEGER,
  ZI_BILLNUMBER INTEGER,
  ZI_ENDOFDAYEND INTEGER,
  ZI_ENDOFDAYSTART INTEGER,
  ZI_ENDOFDAYSTARTYESTERDAY INTEGER,
  ZI_GRATUITYBEFORETAX INTEGER,
  ZI_GROUPGRATUITYSIZE INTEGER,
  ZI_INITIALBILLNUMBER INTEGER,
  ZI_INITIALORDERNUMBER INTEGER,
  ZI_NUMBEROFSLOTS INTEGER,
  ZI_ORDERNUMBER INTEGER,
  ZI_PARTYNUMBER INTEGER,
  ZI_TABLENUMBER INTEGER,
  ZI_TAX2ONTAX1 INTEGER,
  ZINCLUDETIPOUT INTEGER,
  ZINCLUSIVETAX INTEGER,
  ZISSRMMODE INTEGER,
  ZISSRMTRAININGMODE INTEGER,
  ZMENUMANAGEMENTMODE INTEGER,
  ZPHONEHOME INTEGER,
  ZSHOWSRMMERCHANTCOPYOPTION INTEGER,
  ZSRMTRANSACTIONNUMBER INTEGER,
  ZTAX1TAKEOUTEXCLUSIONS INTEGER,
  ZTAX2TAKEOUTEXCLUSIONS INTEGER,
  ZTAX3TAKEOUTEXCLUSIONS INTEGER,
  ZADVANCEDSETTINGS INTEGER,
  ZBARPRINTER INTEGER,
  ZBILLHEADERSETTINGS INTEGER,
  ZBILLSPRINTER INTEGER,
  ZCHITHEADERSETTINGS INTEGER,
  ZCURRENTBATCHPAYMENT INTEGER,
  ZCURRENTRESTAURANTSHIFT INTEGER,
  ZMENUAPPPRINTER INTEGER,
  ZREGISTERSECTION INTEGER,
  ZREPORTSPRINTER INTEGER,
  ZTAKEOUTSECTION INTEGER,
  ZTOUCHBISTROACCOUNTSETTINGS INTEGER,
  ZUNCATEGORIZEDMENUITEMS INTEGER,
  ZCHECKSUM TIMESTAMP,
  ZDAYSTARTED TIMESTAMP,
  ZI_GRATUITY FLOAT,
  ZI_REDUCEDTAX1 FLOAT,
  ZI_REDUCEDTAX1BILLAMOUNT FLOAT,
  ZI_REDUCEDTAX2 FLOAT,
  ZI_REDUCEDTAX2BILLAMOUNT FLOAT,
  ZI_REDUCEDTAX3 FLOAT,
  ZI_REDUCEDTAX3BILLAMOUNT FLOAT,
  ZI_TAX1 FLOAT,
  ZI_TAX2 FLOAT,
  ZI_TAX3 FLOAT,
  ZLICENSEEXPIRES TIMESTAMP,
  ZMENUEDITDATE TIMESTAMP,
  ZROUNDINGAMOUNT FLOAT,
  ZTIPOUTPERCENTAGE FLOAT,
  ZTRIALEXPIRES TIMESTAMP,
  ZACCEPTEDTOS VARCHAR,
  ZACCESSTOKEN VARCHAR,
  ZADDRESS VARCHAR,
  ZBUSINESSNUMBER VARCHAR,
  ZCITY VARCHAR,
  ZCOUNTRY VARCHAR,
  ZCURRENTCLOUDMENUID VARCHAR,
  ZDAYSTARTEDMANAGER VARCHAR,
  ZEMAIL VARCHAR,
  ZFACEBOOK VARCHAR,
  ZGRATUITYDISPLAYNAME VARCHAR,
  ZLASTMIGRATIONVERSION VARCHAR,
  ZLICENSESECTION VARCHAR,
  ZNAME VARCHAR,
  ZRESTAURANTDESCRIPTION VARCHAR,
  ZSOFTWAREINTEGRATIONPERMISSIONS VARCHAR,
  ZSTATE VARCHAR,
  ZTAX1NAME VARCHAR,
  ZTAX1NUMBER VARCHAR,
  ZTAX2NAME VARCHAR,
  ZTAX2NUMBER VARCHAR,
  ZTAX3NAME VARCHAR,
  ZTAX3NUMBER VARCHAR,
  ZTELEPHONE VARCHAR,
  ZTHANKSINFO VARCHAR,
  ZTIPOUTDISPLAYNAME VARCHAR,
  ZTWITTER VARCHAR,
  ZUUID VARCHAR,
  ZWEBSITE VARCHAR,
  ZZIP VARCHAR,
  ZKDSLICENSES BLOB,
  ZRAWUPVENUEMIGRATIONSTATUS VARCHAR,
  ZVENUEXREFID VARCHAR
);
CREATE TABLE ZLEGACYVENUECHANGEFLAG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZCHANGEFLAG VARCHAR,
  ZRAWTYPE VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE Z_15ROLES (
  Z_15DISCOUNTS INTEGER,
  Z_78ROLES INTEGER,
  PRIMARY KEY (Z_15DISCOUNTS, Z_78ROLES)
);
CREATE TABLE Z_15POSSIBLECATEGORIES (
  Z_15CUSTOMDISCOUNTS INTEGER,
  Z_42POSSIBLECATEGORIES INTEGER,
  PRIMARY KEY (Z_15CUSTOMDISCOUNTS, Z_42POSSIBLECATEGORIES)
);
CREATE TABLE IF NOT EXISTS "Z_44I_PRINTER" (
  Z_44MENUITEMS5 INTEGER,
  Z_66I_PRINTER INTEGER,
  PRIMARY KEY (Z_44MENUITEMS5, Z_66I_PRINTER)
);
CREATE TABLE IF NOT EXISTS "Z_44PROMOTIONS" (
  Z_44MENUITEMS4 INTEGER,
  Z_46PROMOTIONS INTEGER,
  PRIMARY KEY (Z_44MENUITEMS4, Z_46PROMOTIONS)
);
CREATE TABLE ZRESTAURANTSHIFT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZSYNCSTATUS INTEGER,
  ZRESTAURANTINFO INTEGER,
  ZDAYEND TIMESTAMP,
  ZDAYSTART TIMESTAMP,
  ZCLOSINGMANAGER VARCHAR,
  ZOPENINGMANAGER VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE IF NOT EXISTS "Z_74TABLES" (
  Z_74RESERVATIONS INTEGER,
  Z_83TABLES INTEGER,
  PRIMARY KEY (Z_74RESERVATIONS, Z_83TABLES)
);
CREATE TABLE IF NOT EXISTS "Z_32MENUITEMS" (
  Z_32KITCHENDISPLAYS INTEGER,
  Z_44MENUITEMS1 INTEGER,
  PRIMARY KEY (Z_32KITCHENDISPLAYS, Z_44MENUITEMS1)
);
CREATE TABLE IF NOT EXISTS "Z_33MENUITEMS" (
  Z_33KITCHENSTATIONS INTEGER,
  Z_44MENUITEMS2 INTEGER,
  PRIMARY KEY (Z_33KITCHENSTATIONS, Z_44MENUITEMS2)
);
CREATE TABLE IF NOT EXISTS "Z_52I_ORDERITEMS" (
  Z_52I_ORDERS INTEGER,
  Z_53I_ORDERITEMS INTEGER,
  PRIMARY KEY (Z_52I_ORDERS, Z_53I_ORDERITEMS)
);
CREATE TABLE IF NOT EXISTS "Z_52PRINTREFERENCES" (
  Z_52ORDERS INTEGER,
  Z_67PRINTREFERENCES INTEGER,
  PRIMARY KEY (Z_52ORDERS, Z_67PRINTREFERENCES)
);
CREATE TABLE IF NOT EXISTS "Z_67FUTUREREFERENCES" (
  Z_67PASTREFERENCES INTEGER,
  Z_67FUTUREREFERENCES INTEGER,
  PRIMARY KEY (Z_67PASTREFERENCES, Z_67FUTUREREFERENCES)
);
CREATE TABLE Z_2MENUITEMS (
  Z_2ALLERGENS INTEGER,
  Z_44MENUITEMS INTEGER,
  PRIMARY KEY (Z_2ALLERGENS, Z_44MENUITEMS)
);
CREATE TABLE ZVENUECOREMUTATION (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZPERFORMEDAT TIMESTAMP,
  ZBATCHUUID VARCHAR,
  ZMUTATIONENTITYNAME VARCHAR,
  ZRAWMUTATIONTYPE VARCHAR,
  ZRAWPAYLOAD VARCHAR,
  ZRAWUPLOADSTATUS VARCHAR,
  ZUPLOADSTATUSFAILEDMESSAGE VARCHAR,
  ZUUID VARCHAR,
  ZCREATEDAT TIMESTAMP
);
CREATE TABLE ZBATCHPAYMENT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRESTAURANTINFO INTEGER,
  ZENDEDAT TIMESTAMP,
  ZSTARTEDAT TIMESTAMP,
  ZENDEDDURINGRESTAURANTSHIFTUUID VARCHAR,
  ZSTARTEDDURINGRESTAURANTSHIFTUUID VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE IF NOT EXISTS "Z_34ORDERITEMS" (
  Z_34CHITS INTEGER,
  Z_37ORDERITEMS INTEGER,
  PRIMARY KEY (Z_34CHITS, Z_37ORDERITEMS)
);
CREATE TABLE ZPAYMENTGATEWAYTRANSACTIONINFO (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZCARDENTRYMETHOD INTEGER,
  ZDEBITACCOUNTTYPE INTEGER,
  ZLANGUAGECODE INTEGER,
  ZPAYMENTGATEWAYTYPE INTEGER,
  ZSAFSTATE INTEGER,
  ZTRANSACTIONTYPE INTEGER,
  ZPAYMENT INTEGER,
  ZADDITIONALDATA VARCHAR,
  ZAPPROVALCODE VARCHAR,
  ZBASE64STRING VARCHAR,
  ZCMV VARCHAR,
  ZCUSTOMERRECEIPT VARCHAR,
  ZEMVAID VARCHAR,
  ZEMVAPPLICATIONLABEL VARCHAR,
  ZEMVPINSTATEMENT VARCHAR,
  ZEMVPREFERREDNAME VARCHAR,
  ZEMVTSI VARCHAR,
  ZEMVTVR VARCHAR,
  ZISOCODE VARCHAR,
  ZMERCHANTRECEIPT VARCHAR,
  ZRECEIPTID VARCHAR,
  ZREFERENCENUM VARCHAR,
  ZRESPONSECODE VARCHAR,
  ZTERMINALID VARCHAR,
  ZTRANSDATE VARCHAR,
  ZTRANSID VARCHAR,
  ZTRANSTIME VARCHAR,
  ZUUID VARCHAR,
  ZISTERMINALTIP INTEGER,
  ZISOFFLINE INTEGER,
  ZPROVIDERTRANSACTIONXREFID VARCHAR,
  ZTERMINALLABEL VARCHAR,
  ZBATCHID VARCHAR,
  ZTERMINALVERSION VARCHAR,
  ZTERMINALMODEL VARCHAR
);
CREATE TABLE IF NOT EXISTS "Z_42PRINTERS" (
  Z_42MENUCATEGORIES INTEGER,
  Z_66PRINTERS INTEGER,
  PRIMARY KEY (Z_42MENUCATEGORIES, Z_66PRINTERS)
);
CREATE TABLE ZWAITER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBLINDREAD INTEGER,
  ZCANACCESSACCOUNTS INTEGER,
  ZCANCOMPOSEMESSAGE INTEGER,
  ZCANPERFORMRETURNS INTEGER,
  ZCLOCKINONLY INTEGER,
  ZDARKMODE INTEGER,
  ZDISCOUNTPERCENT INTEGER,
  ZENABLEFASTBAR INTEGER,
  ZI_CANACCESSPOINTOFSALE INTEGER,
  ZI_CANACCESSRESERVATIONS INTEGER,
  ZI_CANACCESSTAKEOUT INTEGER,
  ZI_COLOR INTEGER,
  ZI_ISLOCKEDTOFASTBAR INTEGER,
  ZI_PERMISSIONS INTEGER,
  ZISHIDDEN INTEGER,
  ZISPERSONALREGISTERENABLED INTEGER,
  ZREQUIRESCASHTIP INTEGER,
  ZRIGHTHANDMODE INTEGER,
  ZDEFAULTFLOORPLAN INTEGER,
  ZDEFAULTTABLE INTEGER,
  ZPERSONALQUICKREGISTER INTEGER,
  ZRESTAURANT INTEGER,
  ZROLE INTEGER,
  ZSECTION INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZCURRENTCLOCKIN TIMESTAMP,
  ZRATEOFPAYPERHOUR FLOAT,
  ZDISPLAYNAME VARCHAR,
  ZEMAIL VARCHAR,
  ZFIRSTNAME VARCHAR,
  ZLASTNAME VARCHAR,
  ZPASSCODE VARCHAR,
  ZPHONE VARCHAR,
  ZQRCODE VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZVOIDREASON (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRETURNSINVENTORY INTEGER,
  ZTAXABLE INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZTBACCOUNT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZFAVOURITE INTEGER,
  ZCUSTOMER INTEGER,
  Z75ACCOUNTS INTEGER,
  ZARCHIVEDAT TIMESTAMP,
  ZBALANCE FLOAT,
  ZCREATEDATE TIMESTAMP,
  ZEMAIL VARCHAR,
  ZNAME VARCHAR,
  ZNOTE VARCHAR,
  ZNUMBER VARCHAR,
  ZPHONENUMBER VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZTAKEOUT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZDELIVERYINPROGRESS INTEGER,
  ZI_SEEN INTEGER,
  ZI_TYPE INTEGER,
  ZI_UNSYNCEDONLINEORDER INTEGER,
  ZOVERRIDESEATCOUNT INTEGER,
  ZSHOWREMINDER INTEGER,
  ZCUSTOMTAKEOUTTYPE INTEGER,
  ZCUSTOMER INTEGER,
  ZONLINEORDER INTEGER,
  ZORIGINALPAIDORDER INTEGER,
  ZPARTY INTEGER,
  ZWAITER INTEGER,
  Z75I_TAKEOUTORDERS INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZDATE TIMESTAMP,
  ZADDRESS VARCHAR,
  ZCITY VARCHAR,
  ZCOUNTRY VARCHAR,
  ZDELIVERYID VARCHAR,
  ZDRIVERNAME VARCHAR,
  ZEMAIL VARCHAR,
  ZNAME VARCHAR,
  ZNOTE VARCHAR,
  ZPHONENUMBER VARCHAR,
  ZPOSTALCODE VARCHAR,
  ZREGION VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZSECTION (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRESTAURANT INTEGER,
  ZWAITER INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZSEAT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_COLOR INTEGER,
  ZI_INDEX INTEGER,
  ZCUSTOMER INTEGER,
  ZORDER INTEGER,
  Z56I_SEATS INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZGENDER VARCHAR,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZROLE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZBASEPERMISSION INTEGER,
  ZBLINDREAD INTEGER,
  ZBYPASSUNSENTITEMS INTEGER,
  ZCANACCEPTCLOUDMENUCHANGES INTEGER,
  ZCANACCESSACCOUNTS INTEGER,
  ZCANACCESSTABLEIFSAMEROLE INTEGER,
  ZCANCOMPOSEMESSAGE INTEGER,
  ZCANLAUNCHTOUCHBISTRO INTEGER,
  ZCANMANAGEBILL INTEGER,
  ZCANMANAGEDISCOUNTS INTEGER,
  ZCANMANAGEGRATUITY INTEGER,
  ZCANMANAGEMENU INTEGER,
  ZCANMANAGEORDERS INTEGER,
  ZCANMANAGEPAYMENTGATEWAYS INTEGER,
  ZCANMANAGEPURCHASES INTEGER,
  ZCANMANAGEREPORTS INTEGER,
  ZCANMANAGESHIFTS INTEGER,
  ZCANMANAGESTAFF INTEGER,
  ZCANMANAGEVOIDS INTEGER,
  ZCANOPENCASHDRAWER INTEGER,
  ZCANPAYIN INTEGER,
  ZCANPAYOUT INTEGER,
  ZCANPERFORMENDOFDAY INTEGER,
  ZCANPERFORMRETURNS INTEGER,
  ZCANRECEIVESYSTEMNOTIFICATIONS INTEGER,
  ZCLOCKINONLY INTEGER,
  ZENABLEFASTBAR INTEGER,
  ZI_CANACCESSPOINTOFSALE INTEGER,
  ZI_CANACCESSRESERVATIONS INTEGER,
  ZI_CANACCESSTAKEOUT INTEGER,
  ZISADMIN INTEGER,
  ZISARCHIVE INTEGER,
  ZISBACKOFHOUSE INTEGER,
  ZISBARTENDER INTEGER,
  ZISPERSONALREGISTERENABLED INTEGER,
  ZREQUIRESCASHTIP INTEGER,
  ZUSEBARTENDERPRINTER INTEGER,
  ZRESTAURANT INTEGER,
  ZDELETEDAT TIMESTAMP,
  ZMAXPAYINOUT FLOAT,
  ZNAME VARCHAR,
  ZSCHEDULINGINTEGRATIONNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZRESERVATION (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_SIZE INTEGER,
  ZCUSTOMER INTEGER,
  ZDEPOSIT INTEGER,
  Z75I_RESERVATIONS INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZDATE TIMESTAMP,
  ZEMAIL VARCHAR,
  ZNAME VARCHAR,
  ZNOTE VARCHAR,
  ZPHONENUMBER VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZREPORTSTEMPLATE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZNAME VARCHAR,
  ZTEMPLATEDESCRIPTION VARCHAR,
  ZTEMPLATEIDENTIFIER VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPRINTER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZCOPIES INTEGER,
  ZI_PRINTERTYPE INTEGER,
  ZKITCHENBUZZER INTEGER,
  ZORIGINALPRINTERTYPE INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZNAME VARCHAR,
  ZORIGINALIP VARCHAR,
  ZPRINTERIP VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPAYMENTTERMINAL (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZLANE INTEGER,
  ZTYPE INTEGER,
  ZGATEWAYPAYMENTTERMINALCONFIG INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZGIFTCARDECR VARCHAR,
  ZIPADDRESS VARCHAR,
  ZNAME VARCHAR,
  ZPORT VARCHAR,
  ZTERMINALID VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZPAIDORDER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_BILLNUMBER INTEGER,
  ZI_GRATUITYBEFORETAX INTEGER,
  ZI_GROUPNUMBER INTEGER,
  ZI_PARTYSIZE INTEGER,
  ZI_SPLIT INTEGER,
  ZI_TAKEOUTTYPE INTEGER,
  ZI_TAX2ONTAX1 INTEGER,
  ZMAXSEATCOUNT INTEGER,
  ZSECTIONID INTEGER,
  ZSYNCSTATUS INTEGER,
  ZBILLRANGE INTEGER,
  ZCLOSEDTAKEOUT INTEGER,
  ZORDER INTEGER,
  ZPAYMENTS INTEGER,
  ZTABLEORDER INTEGER,
  ZWAITER INTEGER,
  Z75I_PAIDORDERS INTEGER,
  ZI_GRATUITY FLOAT,
  ZI_REDUCEDTAX1 FLOAT,
  ZI_REDUCEDTAX1BILLAMOUNT FLOAT,
  ZI_REDUCEDTAX2 FLOAT,
  ZI_REDUCEDTAX2BILLAMOUNT FLOAT,
  ZI_REDUCEDTAX3 FLOAT,
  ZI_REDUCEDTAX3BILLAMOUNT FLOAT,
  ZI_SPLITBY FLOAT,
  ZI_TAX1 FLOAT,
  ZI_TAX2 FLOAT,
  ZI_TAX3 FLOAT,
  ZLOYALTYCREDITBALANCE FLOAT,
  ZLOYALTYPOINTSBALANCE FLOAT,
  ZLOYALTYPOINTSEARNED FLOAT,
  ZLOYALTYPOINTSREFUNDED FLOAT,
  ZLOYALTYPOINTSUSED FLOAT,
  ZOUTSTANDINGBALANCE FLOAT,
  ZPAYDATE TIMESTAMP,
  ZSEATEDDATE TIMESTAMP,
  ZADDRESS VARCHAR,
  ZBILLRANGEUUID VARCHAR,
  ZBUSINESSNUMBER VARCHAR,
  ZCITY VARCHAR,
  ZCLOSEDATVERSION VARCHAR,
  ZCOUNTRY VARCHAR,
  ZCUSTOMERID VARCHAR,
  ZEMAIL VARCHAR,
  ZLOYALTYACCOUNTNAME VARCHAR,
  ZNAME VARCHAR,
  ZORIGINALPAIDORDERUUID VARCHAR,
  ZPARTYNAME VARCHAR,
  ZPARTYUUID VARCHAR,
  ZRESTAURANTDESCRIPTION VARCHAR,
  ZSECTION VARCHAR,
  ZSTATE VARCHAR,
  ZSYNCEDATVERSION VARCHAR,
  ZTABLENAME VARCHAR,
  ZTAX1NUMBER VARCHAR,
  ZTAX2NUMBER VARCHAR,
  ZTAX3NUMBER VARCHAR,
  ZTELEPHONE VARCHAR,
  ZTHANKSINFO VARCHAR,
  ZUUID VARCHAR,
  ZWAITERUUID VARCHAR,
  ZWEBSITE VARCHAR,
  ZZIP VARCHAR
);
CREATE TABLE ZMODIFIERGROUP (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_REQUIREDSELECTIONS INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZI_IMAGE VARCHAR,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZMENUPROMOTION (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZHIDDEN INTEGER,
  ZISACTIVE INTEGER,
  ZPRICETYPE INTEGER,
  ZRESTAURANT INTEGER,
  ZSCHEDULE INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZPRICE FLOAT,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZMENU (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZHIDDEN INTEGER,
  ZINDEX INTEGER,
  ZSCHEDULE INTEGER,
  Z75MENUS INTEGER,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZKITCHENSTATION (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZINCLUDESEATNUMBER INTEGER,
  ZINSERTCHITSFROMLEFT INTEGER,
  ZREDZONE INTEGER,
  ZTRACKITEMTIME INTEGER,
  ZYELLOWZONE INTEGER,
  Z75KITCHENSTATIONS INTEGER,
  ZVERSION FLOAT,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZKITCHENDISPLAY (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZIPADDRESS VARCHAR,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZITEMTYPE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZTYPEID INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZFLOORPLAN (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_CUSTOMFLOORING INTEGER,
  ZI_FLOORING INTEGER,
  ZI_INDEX INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZI_FLOORIMAGE VARCHAR,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZCUSTOMER (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZGENDER INTEGER,
  ZISVIP INTEGER,
  ZTOTALVISITS INTEGER,
  ZACCOUNT INTEGER,
  ZCUSTOMERINFO INTEGER,
  ZSEAT INTEGER,
  Z75CUSTOMERS INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZLASTVISIT TIMESTAMP,
  ZTOTALPAID FLOAT,
  ZTOTALTIP FLOAT,
  ZADDRESSBOOKID VARCHAR,
  ZDISPLAYNAME VARCHAR,
  ZFIRSTNAME VARCHAR,
  ZLASTNAME VARCHAR,
  ZPAYPALIMAGEURL VARCHAR,
  ZPAYPALID VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZCUSTOMDISCOUNT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZISPERCENT INTEGER,
  ZRESTAURANT INTEGER,
  ZAMOUNT FLOAT,
  ZCREATEDATE TIMESTAMP,
  ZNAME VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZCLOSEDTAKEOUT (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZTYPE INTEGER,
  ZCUSTOMTAKEOUTTYPE INTEGER,
  ZONLINEORDER INTEGER,
  ZPAIDORDER INTEGER,
  ZCREATEDATE TIMESTAMP,
  ZDATE TIMESTAMP,
  ZADDRESS VARCHAR,
  ZCITY VARCHAR,
  ZCOUNTRY VARCHAR,
  ZDRIVERNAME VARCHAR,
  ZEMAIL VARCHAR,
  ZNAME VARCHAR,
  ZNOTE VARCHAR,
  ZPHONENUMBER VARCHAR,
  ZPOSTALCODE VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZBILLRANGE (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZENDOFRANGE INTEGER,
  ZSTARTOFRANGE INTEGER,
  ZSTARTINGBILLNUMBER INTEGER,
  ZSTATUS INTEGER,
  ZRESTAURANT INTEGER,
  ZCREATEDAT TIMESTAMP,
  ZDELETEDAT TIMESTAMP,
  ZENDDATE TIMESTAMP,
  ZEXPIREDAT TIMESTAMP,
  ZSTARTDATE TIMESTAMP,
  ZPREFIX VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE ZGATEWAYPAYMENTTERMINALCONFIG (
  Z_PK INTEGER PRIMARY KEY,
  Z_ENT INTEGER,
  Z_OPT INTEGER,
  ZI_TIPENABLED INTEGER,
  ZPAYMENTTERMINAL INTEGER,
  ZPAYMENTTERMINALMODEL VARCHAR,
  ZPAYMENTTERMINALMODELID VARCHAR,
  ZTIPMODE VARCHAR,
  ZTIPSETTINGS VARCHAR,
  ZUUID VARCHAR
);
CREATE TABLE Z_PRIMARYKEY (
  Z_ENT INTEGER PRIMARY KEY,
  Z_NAME VARCHAR,
  Z_SUPER INTEGER,
  Z_MAX INTEGER
);
CREATE INDEX ZALLERGEN_ZRESTAURANT_INDEX ON ZALLERGEN (ZRESTAURANT);
CREATE INDEX ZCARDTYPE_ZRESTAURANTINFO_INDEX ON ZCARDTYPE (ZRESTAURANTINFO);
CREATE INDEX ZCUSTOMERINFO_ZCUSTOMER_INDEX ON ZCUSTOMERINFO (ZCUSTOMER);
CREATE INDEX ZCUSTOMTAKEOUTTYPE_ZRESTAURANT_INDEX ON ZCUSTOMTAKEOUTTYPE (ZRESTAURANT);
CREATE INDEX ZDEPOSIT_ZRESERVATION_INDEX ON ZDEPOSIT (ZRESERVATION);
CREATE INDEX ZDISCOUNT_ZORDERITEM_INDEX ON ZDISCOUNT (ZORDERITEM);
CREATE INDEX ZGIFTCARDTRANSACTIONLOG_ZWAITER_INDEX ON ZGIFTCARDTRANSACTIONLOG (ZWAITER);
CREATE INDEX ZINGREDIENTFORMENUITEM_ZINGREDIENT_INDEX ON ZINGREDIENTFORMENUITEM (ZINGREDIENT);
CREATE INDEX ZINGREDIENTFORMENUITEM_ZMENUITEM_INDEX ON ZINGREDIENTFORMENUITEM (ZMENUITEM);
CREATE INDEX ZINGREDIENTFORMENUITEM_ZRECIPEMEASURE_INDEX ON ZINGREDIENTFORMENUITEM (ZRECIPEMEASURE);
CREATE INDEX ZINGREDIENTLOG_ZINGREDIENT_INDEX ON ZINGREDIENTLOG (ZINGREDIENT);
CREATE INDEX ZINGREDIENTLOG_ZWAITER_INDEX ON ZINGREDIENTLOG (ZWAITER);
CREATE INDEX ZINGREDIENTSUMMARYLOG_ZINGREDIENT_INDEX ON ZINGREDIENTSUMMARYLOG (ZINGREDIENT);
CREATE INDEX ZINTEGRATION_ZRESTAURANT_INDEX ON ZINTEGRATION (ZRESTAURANT);
CREATE INDEX ZKITCHENSTATIONCHIT_ZORDER_INDEX ON ZKITCHENSTATIONCHIT (ZORDER);
CREATE INDEX ZKITCHENSTATIONCHIT_ZSTATION_INDEX ON ZKITCHENSTATIONCHIT (ZSTATION);
CREATE INDEX ZKITCHENSTATIONMODIFIER_ZPARENTMODIFIER_INDEX ON ZKITCHENSTATIONMODIFIER (ZPARENTMODIFIER);
CREATE INDEX ZKITCHENSTATIONMODIFIER_ZPARENTORDERITEM_INDEX ON ZKITCHENSTATIONMODIFIER (ZPARENTORDERITEM);
CREATE INDEX ZKITCHENSTATIONORDERITEM_ZORDER_INDEX ON ZKITCHENSTATIONORDERITEM (ZORDER);
CREATE INDEX ZLOYALTYACTIVITYLOG_ZWAITER_INDEX ON ZLOYALTYACTIVITYLOG (ZWAITER);
CREATE INDEX ZMENUCATEGORYINFOFORMENUPAGE_ZMENUCATEGORY_INDEX ON ZMENUCATEGORYINFOFORMENUPAGE (ZMENUCATEGORY);
CREATE INDEX ZMENUCATEGORYINFOFORMENUPAGE_ZMENUPAGE_INDEX ON ZMENUCATEGORYINFOFORMENUPAGE (ZMENUPAGE);
CREATE INDEX ZMENUPAGE_ZRESTAURANTINFO_INDEX ON ZMENUPAGE (ZRESTAURANTINFO);
CREATE INDEX ZMENUPAGE_ZTBMENULOCK_INDEX ON ZMENUPAGE (ZTBMENULOCK);
CREATE INDEX ZMODIFIER_ZCONTAINERORDERITEM_INDEX ON ZMODIFIER (ZCONTAINERORDERITEM);
CREATE INDEX ZMODIFIER_ZMENUITEM_INDEX ON ZMODIFIER (ZMENUITEM);
CREATE INDEX ZMODIFIER_ZMODIFIERGROUP_INDEX ON ZMODIFIER (ZMODIFIERGROUP);
CREATE INDEX ZMODIFIER_ZMODIFIERGROUPFORMENUITEM_INDEX ON ZMODIFIER (ZMODIFIERGROUPFORMENUITEM);
CREATE INDEX ZMODIFIER_ZORDERITEM_INDEX ON ZMODIFIER (ZORDERITEM);
CREATE INDEX ZMODIFIERGROUPFORMENUITEM_ZMENUITEM_INDEX ON ZMODIFIERGROUPFORMENUITEM (ZMENUITEM);
CREATE INDEX ZMODIFIERGROUPFORMENUITEM_ZMODIFIERGROUP_INDEX ON ZMODIFIERGROUPFORMENUITEM (ZMODIFIERGROUP);
CREATE INDEX ZONLINEORDER_ZCLOSEDTAKEOUT_INDEX ON ZONLINEORDER (ZCLOSEDTAKEOUT);
CREATE INDEX ZONLINEORDER_ZTAKEOUT_INDEX ON ZONLINEORDER (ZTAKEOUT);
CREATE INDEX ZORDERITEM_ZMENUITEM_INDEX ON ZORDERITEM (ZMENUITEM);
CREATE INDEX ZORDERITEM_ZMENUPAGE_INDEX ON ZORDERITEM (ZMENUPAGE);
CREATE INDEX ZPARTY_ZDEPOSIT_INDEX ON ZPARTY (ZDEPOSIT);
CREATE INDEX ZPARTY_ZORDER_INDEX ON ZPARTY (ZORDER);
CREATE INDEX ZPARTY_ZTABLE_INDEX ON ZPARTY (ZTABLE);
CREATE INDEX ZPARTY_ZTABLEORDER_INDEX ON ZPARTY (ZTABLEORDER);
CREATE INDEX ZPARTY_ZTAKEOUT_INDEX ON ZPARTY (ZTAKEOUT);
CREATE INDEX ZPAYMENT_ZACCOUNT_INDEX ON ZPAYMENT (ZACCOUNT);
CREATE INDEX ZPAYMENT_ZCUSTOMER_INDEX ON ZPAYMENT (ZCUSTOMER);
CREATE INDEX ZPAYMENT_ZPAYMENTGATEWAYTRANSACTIONINFO_INDEX ON ZPAYMENT (ZPAYMENTGATEWAYTRANSACTIONINFO);
CREATE INDEX ZPAYMENT_ZPAYMENTGROUP_INDEX ON ZPAYMENT (ZPAYMENTGROUP);
CREATE INDEX ZPAYMENTLOG_ZACCOUNT_INDEX ON ZPAYMENTLOG (ZACCOUNT);
CREATE INDEX ZPAYMENTS_ZPAIDORDER_INDEX ON ZPAYMENTS (ZPAIDORDER);
CREATE INDEX ZPAYMENTS_ZPARTY_INDEX ON ZPAYMENTS (ZPARTY);
CREATE INDEX ZPAYOUT_ZREASON_INDEX ON ZPAYOUT (ZREASON);
CREATE INDEX ZPAYOUT_ZTABLE_INDEX ON ZPAYOUT (ZTABLE);
CREATE INDEX ZPAYOUT_ZWAITER_INDEX ON ZPAYOUT (ZWAITER);
CREATE INDEX ZPAYOUTREASON_ZRESTAURANT_INDEX ON ZPAYOUTREASON (ZRESTAURANT);
CREATE INDEX ZPERIPHERAL_ZRESTAURANT_INDEX ON ZPERIPHERAL (ZRESTAURANT);
CREATE INDEX ZPREAUTH_ZPAYMENTSOBJECT_INDEX ON ZPREAUTH (ZPAYMENTSOBJECT);
CREATE INDEX ZRECIPEMEASURE_ZINGREDIENT_INDEX ON ZRECIPEMEASURE (ZINGREDIENT);
CREATE INDEX ZREGISTERBUTTON_ZRESTAURANT_INDEX ON ZREGISTERBUTTON (ZRESTAURANT);
CREATE INDEX ZREPORTIDENTIFIER_ZTEMPLATE_INDEX ON ZREPORTIDENTIFIER (ZTEMPLATE);
CREATE INDEX ZRESTAURANTPAYMENTGATEWAY_ZRESTAURANT_INDEX ON ZRESTAURANTPAYMENTGATEWAY (ZRESTAURANT);
CREATE INDEX ZSTOREDPAYMENTMETHOD_ZPARTY_INDEX ON ZSTOREDPAYMENTMETHOD (ZPARTY);
CREATE INDEX ZTABLE_ZBOTTOMCHILD_INDEX ON ZTABLE (ZBOTTOMCHILD);
CREATE INDEX ZTABLE_ZFLOORPLAN_INDEX ON ZTABLE (ZFLOORPLAN);
CREATE INDEX ZTABLE_ZLEFTCHILD_INDEX ON ZTABLE (ZLEFTCHILD);
CREATE INDEX ZTABLE_ZPARENT_INDEX ON ZTABLE (ZPARENT);
CREATE INDEX ZTABLE_ZPARTY_INDEX ON ZTABLE (ZPARTY);
CREATE INDEX ZTABLE_ZRIGHTCHILD_INDEX ON ZTABLE (ZRIGHTCHILD);
CREATE INDEX ZTABLE_ZSECTION_INDEX ON ZTABLE (ZSECTION);
CREATE INDEX ZTABLE_ZTOPCHILD_INDEX ON ZTABLE (ZTOPCHILD);
CREATE INDEX ZTABLE_ZWAITER_INDEX ON ZTABLE (ZWAITER);
CREATE INDEX ZTBMENUSETTING_ZLOCKEDMENU_INDEX ON ZTBMENUSETTING (ZLOCKEDMENU);
CREATE INDEX ZTBSCHEDULE_ZMENU_INDEX ON ZTBSCHEDULE (ZMENU);
CREATE INDEX ZTBSCHEDULE_ZMENUCATEGORY_INDEX ON ZTBSCHEDULE (ZMENUCATEGORY);
CREATE INDEX ZTBSCHEDULE_ZMENUPAGE_INDEX ON ZTBSCHEDULE (ZMENUPAGE);
CREATE INDEX ZTBSCHEDULE_ZMENUPROMOTION_INDEX ON ZTBSCHEDULE (ZMENUPROMOTION);
CREATE INDEX ZWAITERROLE_ZROLE_INDEX ON ZWAITERROLE (ZROLE);
CREATE INDEX ZWAITERROLE_ZWAITER_INDEX ON ZWAITERROLE (ZWAITER);
CREATE INDEX ZWALL_ZFLOORPLAN_INDEX ON ZWALL (ZFLOORPLAN);
CREATE INDEX ZMENUITEM_ZCATEGORY_INDEX ON ZMENUITEM (ZCATEGORY);
CREATE INDEX ZMENUITEM_ZREQUIRESVALIDATIONONKIOSK_INDEX ON ZMENUITEM (ZREQUIRESVALIDATIONONKIOSK);
CREATE INDEX ZMENUITEM_ZRESTAURANT_INDEX ON ZMENUITEM (ZRESTAURANT);
CREATE INDEX ZAPPLIEDBREAK_ZSHIFT_INDEX ON ZAPPLIEDBREAK (ZSHIFT);
CREATE INDEX ZSHIFT_ZSTAFFROLE_INDEX ON ZSHIFT (ZSTAFFROLE);
CREATE INDEX ZSHIFT_ZWAITER_INDEX ON ZSHIFT (ZWAITER);
CREATE INDEX ZMENUCATEGORY_ZHIDDENSCHEDULE_INDEX ON ZMENUCATEGORY (ZHIDDENSCHEDULE);
CREATE INDEX ZMENUCATEGORY_ZKITCHENDISPLAY_INDEX ON ZMENUCATEGORY (ZKITCHENDISPLAY);
CREATE INDEX ZMENUCATEGORY_ZPRINTER_INDEX ON ZMENUCATEGORY (ZPRINTER);
CREATE INDEX ZMENUCATEGORY_ZRESTAURANTINFOASUNUSED_INDEX ON ZMENUCATEGORY (ZRESTAURANTINFOASUNUSED);
CREATE INDEX ZMENUCATEGORY_ZRESTAURANTINFOASUSED_INDEX ON ZMENUCATEGORY (ZRESTAURANTINFOASUSED);
CREATE INDEX ZMENUCATEGORY_ZSTATION_INDEX ON ZMENUCATEGORY (ZSTATION);
CREATE INDEX ZORDER_ZPAIDORDER_INDEX ON ZORDER (ZPAIDORDER);
CREATE INDEX ZORDER_ZPARTY_INDEX ON ZORDER (ZPARTY);
CREATE INDEX ZORDER_ZPARTYASSPLITORDER_INDEX ON ZORDER (ZPARTYASSPLITORDER);
CREATE INDEX ZORDER_ZTEMPPARTY_INDEX ON ZORDER (ZTEMPPARTY);
CREATE INDEX Z_2MENUITEMS_Z_43MENUITEMS_INDEX ON Z_2MENUITEMS (Z_44MENUITEMS, Z_2ALLERGENS);
CREATE INDEX ZBATCHPAYMENT_ZRESTAURANTINFO_INDEX ON ZBATCHPAYMENT (ZRESTAURANTINFO);
CREATE INDEX Z_15ROLES_Z_77ROLES_INDEX ON Z_15ROLES (Z_78ROLES, Z_15DISCOUNTS);
CREATE INDEX Z_15POSSIBLECATEGORIES_Z_41POSSIBLECATEGORIES_INDEX ON Z_15POSSIBLECATEGORIES (Z_42POSSIBLECATEGORIES, Z_15CUSTOMDISCOUNTS);
CREATE INDEX Z_31MENUITEMS_Z_43MENUITEMS1_INDEX ON "Z_32MENUITEMS" (Z_44MENUITEMS1, Z_32KITCHENDISPLAYS);
CREATE INDEX Z_32MENUITEMS_Z_43MENUITEMS2_INDEX ON "Z_33MENUITEMS" (Z_44MENUITEMS2, Z_33KITCHENSTATIONS);
CREATE INDEX Z_33ORDERITEMS_Z_36ORDERITEMS_INDEX ON "Z_34ORDERITEMS" (Z_37ORDERITEMS, Z_34CHITS);
CREATE INDEX Z_39MENUITEMS_Z_43MENUITEMS3_INDEX ON "Z_40MENUITEMS" (Z_44MENUITEMS3, Z_40MENU);
CREATE INDEX Z_41PRINTERS_Z_65PRINTERS_INDEX ON "Z_42PRINTERS" (Z_66PRINTERS, Z_42MENUCATEGORIES);
CREATE INDEX Z_43I_PRINTER_Z_65I_PRINTER_INDEX ON "Z_44I_PRINTER" (Z_66I_PRINTER, Z_44MENUITEMS5);
CREATE INDEX Z_43PROMOTIONS_Z_45PROMOTIONS_INDEX ON "Z_44PROMOTIONS" (Z_46PROMOTIONS, Z_44MENUITEMS4);
CREATE INDEX Z_51I_ORDERITEMS_Z_52I_ORDERITEMS_INDEX ON "Z_52I_ORDERITEMS" (Z_53I_ORDERITEMS, Z_52I_ORDERS);
CREATE INDEX Z_51PRINTREFERENCES_Z_66PRINTREFERENCES_INDEX ON "Z_52PRINTREFERENCES" (Z_67PRINTREFERENCES, Z_52ORDERS);
CREATE INDEX ZPAYMENTGATEWAYTRANSACTIONINFO_ZPAYMENT_INDEX ON ZPAYMENTGATEWAYTRANSACTIONINFO (ZPAYMENT);
CREATE INDEX Z_66FUTUREREFERENCES_Z_66FUTUREREFERENCES_INDEX ON "Z_67FUTUREREFERENCES" (Z_67FUTUREREFERENCES, Z_67PASTREFERENCES);
CREATE INDEX Z_73TABLES_Z_82TABLES_INDEX ON "Z_74TABLES" (Z_83TABLES, Z_74RESERVATIONS);
CREATE INDEX ZRESTAURANTINFO_ZADVANCEDSETTINGS_INDEX ON ZRESTAURANTINFO (ZADVANCEDSETTINGS);
CREATE INDEX ZRESTAURANTINFO_ZBARPRINTER_INDEX ON ZRESTAURANTINFO (ZBARPRINTER);
CREATE INDEX ZRESTAURANTINFO_ZBILLHEADERSETTINGS_INDEX ON ZRESTAURANTINFO (ZBILLHEADERSETTINGS);
CREATE INDEX ZRESTAURANTINFO_ZBILLSPRINTER_INDEX ON ZRESTAURANTINFO (ZBILLSPRINTER);
CREATE INDEX ZRESTAURANTINFO_ZCHITHEADERSETTINGS_INDEX ON ZRESTAURANTINFO (ZCHITHEADERSETTINGS);
CREATE INDEX ZRESTAURANTINFO_ZCURRENTBATCHPAYMENT_INDEX ON ZRESTAURANTINFO (ZCURRENTBATCHPAYMENT);
CREATE INDEX ZRESTAURANTINFO_ZCURRENTRESTAURANTSHIFT_INDEX ON ZRESTAURANTINFO (ZCURRENTRESTAURANTSHIFT);
CREATE INDEX ZRESTAURANTINFO_ZMENUAPPPRINTER_INDEX ON ZRESTAURANTINFO (ZMENUAPPPRINTER);
CREATE INDEX ZRESTAURANTINFO_ZREGISTERSECTION_INDEX ON ZRESTAURANTINFO (ZREGISTERSECTION);
CREATE INDEX ZRESTAURANTINFO_ZREPORTSPRINTER_INDEX ON ZRESTAURANTINFO (ZREPORTSPRINTER);
CREATE INDEX ZRESTAURANTINFO_ZTAKEOUTSECTION_INDEX ON ZRESTAURANTINFO (ZTAKEOUTSECTION);
CREATE INDEX ZRESTAURANTINFO_ZTOUCHBISTROACCOUNTSETTINGS_INDEX ON ZRESTAURANTINFO (ZTOUCHBISTROACCOUNTSETTINGS);
CREATE INDEX ZRESTAURANTINFO_ZUNCATEGORIZEDMENUITEMS_INDEX ON ZRESTAURANTINFO (ZUNCATEGORIZEDMENUITEMS);
CREATE INDEX ZRESTAURANTSHIFT_ZRESTAURANTINFO_INDEX ON ZRESTAURANTSHIFT (ZRESTAURANTINFO);
CREATE INDEX Z_AppliedBreak_shiftUUID ON ZAPPLIEDBREAK (ZSHIFTUUID COLLATE BINARY ASC);
CREATE INDEX Z_AppliedBreak_uuid ON ZAPPLIEDBREAK (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_BatchPayment_uuid ON ZBATCHPAYMENT (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_BreakType_uuid ON ZBREAKTYPE (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_Discount_uuid ON ZDISCOUNT (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_MenuCategory_uuid ON ZMENUCATEGORY (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_MenuItem_uuid ON ZMENUITEM (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_Modifier_uuid ON ZMODIFIER (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_ModifierGroupForMenuItem_uuid ON ZMODIFIERGROUPFORMENUITEM (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_OnlineOrder_stateNew ON ZONLINEORDER (ZSTATENEW COLLATE BINARY ASC);
CREATE INDEX Z_OnlineOrder_uuid ON ZONLINEORDER (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_OrderItem_uuid ON ZORDERITEM (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_Party_uuid ON ZPARTY (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_Payments_uuid ON ZPAYMENTS (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_RestaurantShift_uuid ON ZRESTAURANTSHIFT (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_Shift_uuid ON ZSHIFT (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_2MENUITEMS_Z_44MENUITEMS_INDEX ON Z_2MENUITEMS (Z_44MENUITEMS, Z_2ALLERGENS);
CREATE INDEX ZBILLRANGE_ZRESTAURANT_INDEX ON ZBILLRANGE (ZRESTAURANT);
CREATE INDEX ZCLOSEDTAKEOUT_ZCUSTOMTAKEOUTTYPE_INDEX ON ZCLOSEDTAKEOUT (ZCUSTOMTAKEOUTTYPE);
CREATE INDEX ZCLOSEDTAKEOUT_ZONLINEORDER_INDEX ON ZCLOSEDTAKEOUT (ZONLINEORDER);
CREATE INDEX ZCLOSEDTAKEOUT_ZPAIDORDER_INDEX ON ZCLOSEDTAKEOUT (ZPAIDORDER);
CREATE INDEX Z_ClosedTakeout_uuid ON ZCLOSEDTAKEOUT (ZUUID COLLATE BINARY ASC);
CREATE INDEX ZCUSTOMDISCOUNT_ZRESTAURANT_INDEX ON ZCUSTOMDISCOUNT (ZRESTAURANT);
CREATE INDEX Z_15ROLES_Z_78ROLES_INDEX ON Z_15ROLES (Z_78ROLES, Z_15DISCOUNTS);
CREATE INDEX Z_15POSSIBLECATEGORIES_Z_42POSSIBLECATEGORIES_INDEX ON Z_15POSSIBLECATEGORIES (Z_42POSSIBLECATEGORIES, Z_15CUSTOMDISCOUNTS);
CREATE INDEX ZCUSTOMER_ZACCOUNT_INDEX ON ZCUSTOMER (ZACCOUNT);
CREATE INDEX ZCUSTOMER_ZCUSTOMERINFO_INDEX ON ZCUSTOMER (ZCUSTOMERINFO);
CREATE INDEX ZCUSTOMER_ZSEAT_INDEX ON ZCUSTOMER (ZSEAT);
CREATE INDEX ZCUSTOMER_Z75CUSTOMERS_INDEX ON ZCUSTOMER (Z75CUSTOMERS);
CREATE INDEX ZFLOORPLAN_ZRESTAURANT_INDEX ON ZFLOORPLAN (ZRESTAURANT);
CREATE INDEX ZGATEWAYPAYMENTTERMINALCONFIG_ZPAYMENTTERMINAL_INDEX ON ZGATEWAYPAYMENTTERMINALCONFIG (ZPAYMENTTERMINAL);
CREATE INDEX ZITEMTYPE_ZRESTAURANT_INDEX ON ZITEMTYPE (ZRESTAURANT);
CREATE INDEX ZKITCHENDISPLAY_ZRESTAURANT_INDEX ON ZKITCHENDISPLAY (ZRESTAURANT);
CREATE INDEX Z_32MENUITEMS_Z_44MENUITEMS1_INDEX ON Z_32MENUITEMS (Z_44MENUITEMS1, Z_32KITCHENDISPLAYS);
CREATE INDEX ZKITCHENSTATION_Z75KITCHENSTATIONS_INDEX ON ZKITCHENSTATION (Z75KITCHENSTATIONS);
CREATE INDEX Z_33MENUITEMS_Z_44MENUITEMS2_INDEX ON Z_33MENUITEMS (Z_44MENUITEMS2, Z_33KITCHENSTATIONS);
CREATE INDEX Z_34ORDERITEMS_Z_37ORDERITEMS_INDEX ON Z_34ORDERITEMS (Z_37ORDERITEMS, Z_34CHITS);
CREATE INDEX ZMENU_ZSCHEDULE_INDEX ON ZMENU (ZSCHEDULE);
CREATE INDEX ZMENU_Z75MENUS_INDEX ON ZMENU (Z75MENUS);
CREATE INDEX Z_40MENUITEMS_Z_44MENUITEMS3_INDEX ON Z_40MENUITEMS (Z_44MENUITEMS3, Z_40MENU);
CREATE INDEX Z_42PRINTERS_Z_66PRINTERS_INDEX ON Z_42PRINTERS (Z_66PRINTERS, Z_42MENUCATEGORIES);
CREATE INDEX Z_44I_PRINTER_Z_66I_PRINTER_INDEX ON Z_44I_PRINTER (Z_66I_PRINTER, Z_44MENUITEMS5);
CREATE INDEX Z_44PROMOTIONS_Z_46PROMOTIONS_INDEX ON Z_44PROMOTIONS (Z_46PROMOTIONS, Z_44MENUITEMS4);
CREATE INDEX ZMENUPROMOTION_ZRESTAURANT_INDEX ON ZMENUPROMOTION (ZRESTAURANT);
CREATE INDEX ZMENUPROMOTION_ZSCHEDULE_INDEX ON ZMENUPROMOTION (ZSCHEDULE);
CREATE INDEX ZMODIFIERGROUP_ZRESTAURANT_INDEX ON ZMODIFIERGROUP (ZRESTAURANT);
CREATE INDEX Z_ModifierGroup_uuid ON ZMODIFIERGROUP (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_52I_ORDERITEMS_Z_53I_ORDERITEMS_INDEX ON Z_52I_ORDERITEMS (Z_53I_ORDERITEMS, Z_52I_ORDERS);
CREATE INDEX Z_52PRINTREFERENCES_Z_67PRINTREFERENCES_INDEX ON Z_52PRINTREFERENCES (Z_67PRINTREFERENCES, Z_52ORDERS);
CREATE INDEX Z_Order_uuid ON ZORDER (ZUUID COLLATE BINARY ASC);
CREATE INDEX ZPAIDORDER_ZBILLRANGE_INDEX ON ZPAIDORDER (ZBILLRANGE);
CREATE INDEX ZPAIDORDER_ZCLOSEDTAKEOUT_INDEX ON ZPAIDORDER (ZCLOSEDTAKEOUT);
CREATE INDEX ZPAIDORDER_ZORDER_INDEX ON ZPAIDORDER (ZORDER);
CREATE INDEX ZPAIDORDER_ZPAYMENTS_INDEX ON ZPAIDORDER (ZPAYMENTS);
CREATE INDEX ZPAIDORDER_ZTABLEORDER_INDEX ON ZPAIDORDER (ZTABLEORDER);
CREATE INDEX ZPAIDORDER_ZWAITER_INDEX ON ZPAIDORDER (ZWAITER);
CREATE INDEX ZPAIDORDER_Z75I_PAIDORDERS_INDEX ON ZPAIDORDER (Z75I_PAIDORDERS);
CREATE INDEX Z_PaidOrder_uuid ON ZPAIDORDER (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_Payment_uuid ON ZPAYMENT (ZUUID COLLATE BINARY ASC);
CREATE INDEX Z_PaymentGatewayTransactionInfo_uuid ON ZPAYMENTGATEWAYTRANSACTIONINFO (ZUUID COLLATE BINARY ASC);
CREATE INDEX ZPAYMENTTERMINAL_ZGATEWAYPAYMENTTERMINALCONFIG_INDEX ON ZPAYMENTTERMINAL (ZGATEWAYPAYMENTTERMINALCONFIG);
CREATE INDEX ZPAYMENTTERMINAL_ZRESTAURANT_INDEX ON ZPAYMENTTERMINAL (ZRESTAURANT);
CREATE INDEX ZPRINTER_ZRESTAURANT_INDEX ON ZPRINTER (ZRESTAURANT);
CREATE INDEX Z_67FUTUREREFERENCES_Z_67FUTUREREFERENCES_INDEX ON Z_67FUTUREREFERENCES (Z_67FUTUREREFERENCES, Z_67PASTREFERENCES);
CREATE INDEX ZREPORTSTEMPLATE_ZRESTAURANT_INDEX ON ZREPORTSTEMPLATE (ZRESTAURANT);
CREATE INDEX ZRESERVATION_ZCUSTOMER_INDEX ON ZRESERVATION (ZCUSTOMER);
CREATE INDEX ZRESERVATION_ZDEPOSIT_INDEX ON ZRESERVATION (ZDEPOSIT);
CREATE INDEX ZRESERVATION_Z75I_RESERVATIONS_INDEX ON ZRESERVATION (Z75I_RESERVATIONS);
CREATE INDEX Z_74TABLES_Z_83TABLES_INDEX ON Z_74TABLES (Z_83TABLES, Z_74RESERVATIONS);
CREATE INDEX ZROLE_ZRESTAURANT_INDEX ON ZROLE (ZRESTAURANT);
CREATE INDEX ZSEAT_ZCUSTOMER_INDEX ON ZSEAT (ZCUSTOMER);
CREATE INDEX ZSEAT_ZORDER_INDEX ON ZSEAT (ZORDER);
CREATE INDEX ZSEAT_Z56I_SEATS_INDEX ON ZSEAT (Z56I_SEATS);
CREATE INDEX ZSECTION_ZRESTAURANT_INDEX ON ZSECTION (ZRESTAURANT);
CREATE INDEX ZSECTION_ZWAITER_INDEX ON ZSECTION (ZWAITER);
CREATE INDEX ZTAKEOUT_ZCUSTOMTAKEOUTTYPE_INDEX ON ZTAKEOUT (ZCUSTOMTAKEOUTTYPE);
CREATE INDEX ZTAKEOUT_ZCUSTOMER_INDEX ON ZTAKEOUT (ZCUSTOMER);
CREATE INDEX ZTAKEOUT_ZONLINEORDER_INDEX ON ZTAKEOUT (ZONLINEORDER);
CREATE INDEX ZTAKEOUT_ZORIGINALPAIDORDER_INDEX ON ZTAKEOUT (ZORIGINALPAIDORDER);
CREATE INDEX ZTAKEOUT_ZPARTY_INDEX ON ZTAKEOUT (ZPARTY);
CREATE INDEX ZTAKEOUT_ZWAITER_INDEX ON ZTAKEOUT (ZWAITER);
CREATE INDEX ZTAKEOUT_Z75I_TAKEOUTORDERS_INDEX ON ZTAKEOUT (Z75I_TAKEOUTORDERS);
CREATE INDEX ZTBACCOUNT_ZCUSTOMER_INDEX ON ZTBACCOUNT (ZCUSTOMER);
CREATE INDEX ZTBACCOUNT_Z75ACCOUNTS_INDEX ON ZTBACCOUNT (Z75ACCOUNTS);
CREATE INDEX ZVOIDREASON_ZRESTAURANT_INDEX ON ZVOIDREASON (ZRESTAURANT);
CREATE INDEX ZWAITER_ZDEFAULTFLOORPLAN_INDEX ON ZWAITER (ZDEFAULTFLOORPLAN);
CREATE INDEX ZWAITER_ZDEFAULTTABLE_INDEX ON ZWAITER (ZDEFAULTTABLE);
CREATE INDEX ZWAITER_ZPERSONALQUICKREGISTER_INDEX ON ZWAITER (ZPERSONALQUICKREGISTER);
CREATE INDEX ZWAITER_ZRESTAURANT_INDEX ON ZWAITER (ZRESTAURANT);
CREATE INDEX ZWAITER_ZROLE_INDEX ON ZWAITER (ZROLE);
CREATE INDEX ZWAITER_ZSECTION_INDEX ON ZWAITER (ZSECTION);